service:
- docker

env:
  global:
  - TERM=dumb
  - secure: rs34wHwsLTKMWTxLhfyWe7lbaYadcSAo0lyTxBdHinhH82ohWGVYpV7Zm3pbBH15BZv65pvqspgm2oNOExHBonZ1yhn3VUreso+4h+nf8mAwCjH+71MNTeuQo+d8Jky3SIeLvf4LqYZ6Zbf8yXksPF3DFG49M1S1KByIPmF+LT08pbZEptrsb+T6tuAIyWqMosx4Y4mKub9IgFjudtw42yd+sE4kihpVhW9ebw3wrZYtREXuZxIDfIvvjC+n5cEs0plm41725CVTv893WU6P3Kl0Gtkl6mER6HDLYPIKnSBrDFKvnmMSD7Sc3w/wPFaxfRayC4LB2til324+IcmFq8EeQ7mKRsEwQiIqWra8702/5v9+JH4JntO5lS8cs5osMEv7bf1+bI4+AFTb4S2PqjWFwuvts2yLOZ3tmpFMjHK666+Jaa63JBSVA4+Bhjn2+9hAeIVxhQuiT5oZ3fenHFC8cZV/ywDqjSWfzgoEWJNfiBAfl/ZQRgt1JBFSJrCVjaYIoqscj64L89KMzBu0wrkuepU3n4gJMGPX+7cv4CHcrzCXX3f3mpfiP58swfCh2bNNhuR1xCu7Yyus2UsFcrI5ell4b84Hl1nkY6pOZhr9cwiylSHkBM2TEZQlCRLqbATaFK8/4GpDcCjFey6tyrg6tqhflND+oiiR3WZQYo0=

language: java
jdk: oraclejdk8

install: true
before_script:
- sudo apt update -y >/dev/null 2>&1 || true
- sudo apt install -y --no-install-recommends bash unzip curl jq libxml2-utils docker-ce python-pip >/dev/null 2>&1
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80 5432 1521

script:
- bash gradlew >/dev/null 2>&1
- bash gradlew composeUp -Pprofile=all
- bash ./build/libs/*.jar &
- wait_for 8080
- http :8080
- http :8080/ query="select 1 from dual" springJpaDatabase=ORACLE springDatasourceUrl="jdbc:oracle:thin:@//127.0.0.1:1521/xe" springDatasourceUsername=system springDatasourcePassword=oraclepassword springDatasourceClassName="oracle.jdbc.OracleDriver"
- http :8080/ query="select 1" springJpaDatabase=POSTGRESQL springDatasourceUrl="jdbc:postgresql://0.0.0.0:5432/postgresdatabase" springDatasourceUsername=postgresuser springDatasourcePassword=postgrespassword springDatasourceClassName="org.postgresql.Driver"
- http :8080
- stop_any 8080 80
#
- bash ./target/*.jar &
- wait_for 8080
- http :8080
- http :8080/ query="select 1" springJpaDatabase=POSTGRESQL springDatasourceUrl="jdbc:postgresql://0.0.0.0:5432/postgresdatabase" springDatasourceUsername=postgresuser springDatasourcePassword=postgrespassword springDatasourceClassName="org.postgresql.Driver"
- http :8080/ query="select 1 from dual" springJpaDatabase=ORACLE springDatasourceUrl="jdbc:oracle:thin:@//127.0.0.1:1521/xe" springDatasourceUsername=system springDatasourcePassword=oraclepassword springDatasourceClassName="oracle.jdbc.OracleDriver"
- http :8080
- stop_any 8080 80
- bash gradlew composeDown

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
