version: "2.1"

services:
  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_DB: postgresdatabase
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
    ports: ["5432:5432"]
    networks: [backing-services]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 2s
      retries: 22
    #restart: unless-stopped
    #mem_limit: 786432000 # container limit: 700Mb (700 * 1024 * 1024)

networks:
  backing-services:
    driver: bridge
