app:
  dbs:
    postgres:
      spring-jpa-database: POSTGRESQL
      spring-datasource-url: jdbc:postgresql://127.0.0.1:5432/postgresdatabase
      spring-datasource-password: postgrespassword
      spring-datasource-username: postgresuser
      spring-datasource-driver-class-name: org.postgresql.Driver
    oracle:
      spring-jpa-database: ORACLE
      spring-datasource-url: jdbc:oracle:thin:@//127.0.0.1:1521/xe
      spring-datasource-username: system
      spring-datasource-password: oraclepassword
      spring-datasource-driver-class-name: oracle.jdbc.OracleDriver
    mysql:
      spring-jpa-database: MYSQL
      spring-datasource-url: jdbc:mysql://127.0.0.1:3306/mysqldatabase
      spring-datasource-password: mysqlpassword
      spring-datasource-username: mysqluser
      spring-datasource-driver-class-name: com.mysql.jdbc.Driver
